<link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css">
<link rel="stylesheet" href="/assets/front/css/animate.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<link rel="stylesheet" href="/assets/front/css/owl.theme.default.min.css">
<link rel="stylesheet" href="/assets/front/css/magnific-popup.css">
<link rel="stylesheet" href="/assets/front/css/aos.css">
<link rel="stylesheet" href="/assets/front/css/ionicons.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css">
<link rel="stylesheet" href="/assets/front/css/flaticon.css">
<link rel="stylesheet" href="/assets/front/css/icomoon.css">
<link rel="stylesheet" href="/assets/front/css/style.css">